index:
    path: /
    controller: App\Controller\DefaultController::index

books:
    path: /my/books/
    controller: App\Controller\DefaultController::viewBooks
add_book:
    path: /my/editbooks/0
    controller: App\Controller\DefaultController::editBook
edit_book:
    path: /my/editbooks/{id}
    controller: App\Controller\DefaultController::editBook
